name = "GeometricFlux"
uuid = "7e08b658-56d3-11e9-2997-919d5b31e4ea"
authors = ["Yueh-Hua Tu <a504082002@gmail.com>"]
version = "0.6.1"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
ScatterNNlib = "b1168b60-8710-48c1-88d2-5c53ae207dd0"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
ZygoteRules = "700de1a5-db45-46bc-99cf-38207098b444"

[compat]
CUDA = "1.2"
DataStructures = "0.17"
FillArrays = "0.8 - 0.9"
Flux = "0.10 - 0.11"
LightGraphs = "1.3"
MetaGraphs = "0.6"
Requires = "1.0.0"
SimpleWeightedGraphs = "1.1"
StaticArrays = "0.12"
Zygote = "0.4 - 0.5"
ZygoteRules = "0.2"
julia = "1.4 - 1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
